#pragma once

typedef enum eENUM_CLASS_TYPE
{
	CLASS_TYPE_WARRIOR	= 1,
	CLASS_TYPE_PRIEST	= 2,
	CLASS_TYPE_SUMMONER = 3,
	CLASS_TYPE_HUNTER	= 4,
	CLASS_TYPE_WIZARD	= 5,
	CLASS_TYPE_MAX,
}CLASS_TYPE;

typedef enum eDungeonType
{
	DUNGEON_TYPE_VILLAGE				= 1,
	DUNGEON_TYPE_CONQUER				= 2,
	DUNGEON_TYPE_NOT_CONQUER			= 3,
	DUNGEON_TYPE_TUNNEL					= 4,
	DUNGEON_TYPE_MATCH					= 5,
	DUNGEON_TYPE_NPC					= 6,
	DUNGEON_TYPE_EVENT					= 50,
	DUNGEON_TYPE_MATCH_STATIDUM			= 60,//길드전 장소
}DUNGEON_TYPE;

typedef enum eDungeonOperationMode
{
	OPERATION_DEFENCE					= 0,		// 방어모드
	OPERATION_LEVELUP					= 1,		// 레벨업 모드
	OPERATION_PRODUCTION				= 2			// 생산품모드
}DUNGEON_OPERATION_MODE;

typedef enum eDungeonOperationtype
{
	DUNGEON_OPERATIONTYPE_PRECOCIOUS = 0,
	DUNGEON_OPERATIONTYPE_PRODUCTION = 1,
	DUNGEON_OPERATIONTYPE_CONVERSION = 2,
}DUNGEON_OPERATIONTYPE;

typedef enum eEVENT_DUNGEON_TYPE
{
	EVENT_DUNGEON_DEV_TEST		= 0,
	EVENT_DUNGEON_TRAINING		= 1,
	EVENT_DUNGEON_SURVIVAL		= 2	
}EVENT_DUNGEON_TYPE;

typedef enum eEVENT_DUNGEON_STATE
{
	EVENT_DUNGEON_CLOSE			= 0,	// 열리지 않음.
	EVENT_DUNGEON_READY			= 1,	// 열리기 위해 준비중
	EVENT_DUNGEON_OPEN			= 2,	// 열림.
	EVENT_DUNGEON_OPEN_FULL		= 3,	// 열려있으나, 이벤트 던젼에 유저가 가득 차있음, 
	EVENT_DUNGEON_OPEN_TIME_UP	= 4,	// 열려있으나, 입구가 폐쇄될 시간이 지난 상태.	
	EVENT_DUNGEON_FIRST_CLOSE	= 5		// 열려 있고 1차이벤트가 종료 
}EVENT_DUNGEON_STATE;

typedef enum eEVENT_DUNGEON_DISPLAY_STATE
{
	EVENT_DUNGEON_DISPLAY_OPENNING,			// 열리는 중.
	EVENT_DUNGEON_DISPLAY_CLOSING,			// 닫히는 중.
	EVENT_DUNGEON_DISPLAY_NONE				// 암것도 아님.
}EVENT_DUNGEON_DISPLAY_STATE;

typedef enum eDUNGEON_PROPERTY
{
	DUNGEON_PROPERTY_FIRE = 1,
	DUNGEON_PROPERTY_ICE = 2,
	DUNGEON_PROPERTY_LIGHT = 3,
	
	DUNGEON_PROPERTY_MAX = 30// : hwoarang 던전 속성 30개로 늘림
}DUNGEON_PROPERTY;

typedef enum eDUNGEON_TEMP
{
	DUNGEON_TEMP_PKMODE			= 0,
	DUNGEON_TEMP_CHAT_DISABLE	= 1,
	DUNGEON_TEMP_MAX
}DUNGEON_TEMP;


#define EVENT_DUNGEON_POS_TYPE_NORMAL	0
#define EVENT_DUNGEON_POS_TYPE_SPECIAL	1
#define MAX_EVENT_DUNGEON_NUMBER		16
#define MAX_EVENT_POS_NUMBER			128
#define MAX_EVENT_DUNGEON_KIND			16

DUNGEON_TYPE DECLSPECIFIER DungeonIDtoType(const DWORD dwID);