#pragma once


enum SERVER_TYPE
{
	SERVER_TYPE_LOGINAGENT				= 0,
	SERVER_TYPE_WORLD					= 1,
	SERVER_TYPE_DUNGEON					= 2,
	SERVER_TYPE_VILLAGE					= 3,
};


enum SERVER_TYPE_DUNGEON_VALUE
{
	SERVER_TYPE_NON_OCCUPIED_DUNGEON	= 1,
	SERVER_TYPE_OCCUPIED_DUNGEON		= 2,
	SERVER_TYPE_PATHWAY_DUNGEON			= 4,
};


enum SERVER_STATUS
{
	SERVER_STATUS_NOT_CONNECTED			= 0,
	SERVER_STATUS_CONNECTED				= 1,
};


enum EN_USER_STATUS
{
	USER_STATUS_NORMAL					= 0,
	USER_STATUS_AWAITING_AUTH			= 1,
	USER_STATUS_LOGIN_SUCCESS			= 2,
	USER_STATUS_LOGIN_FAILED			= 3,
	USER_STATUS_CHARACTER_SELECTED		= 4,			//캐릭터를 선택하고 월드서버의 Accept허용을 대기하고 있는상태
	USER_STATUS_AWAITING_WORLD_CONNECT	= 5,			//월드서버의 Accept허용을 받고 월드맵의 로그인 Success를 대기하고 있는상태 
	USER_STATUS_GAME_STARTED			= 6,			//정상적으로 월드로 들어가 게임을 시작했음 	 
};


enum USER_BILLING_FLAG
{
	USER_BILLING_FLAT_RATE				= 2,			//개인 정액
	USER_BILLING_METER_RATE				= 4,			//개인 종량 
	USER_BILLING_1HOUR_FREE				= 9,			//결제 유저 아님 
	USER_BILLING_ABSOLUTELY_FREE		= 10,			//무조건 통과 
	USER_BILLING_COUPON					= 40,			//개인 쿠폰 유저 
};


enum PCROOM_BILLING_FLAG
{
	PCROOM_BILLING_FLAT_RATE			= 1,			//PC방 정액
	PCROOM_BILLING_METER_RATE			= 3,			//PC방 종량
	
		PCROOM_BILLING_SOMEHOUR_FREE	= 11,			//대만용 PC 방 빌링안하고 FREE TIME 적용 
};


enum LOGIN_FAIL_VALUE
{
	LOGIN_FAIL_NO_PAY						= 0,
	LOGIN_FAIL_NO_ID						= 2,
	LOGIN_FAIL_INVALID_PASSWORD				= 3,
	LOGIN_FAIL_OVERLAPPED_ID				= 4,
	LOGIN_FAIL_USER_BLOCK					= 5,
	LOGIN_FAIL_USER_NOT_TEST_ID				= 6,
	LOGIN_FAIL_USER_OVERFLOW				= 8,
	LOGIN_FAIL_INVALID_VERSION				= 9,
	LOGIN_FAIL_NOW_TRY_TO_LOGIN				= 10,
	LOGIN_FAIL_NOT_BETA_TESTER				= 14,		//일본, 베타테스터 아님 
	LOGIN_FAIL_EJECT_USER_JAPAN				= 15,		//일본, 강퇴자 
	LOGIN_FAIL_SECESSION_USER				= 16,		//일본, 탈퇴한 회원
	LOGIN_FAIL_NEXT							= 18,
	LOGIN_FAIL_ETC							= 19,
	LOGIN_FAIL_CHARACTER_OVERLAPPED			= 20,
	LOGIN_FAIL_INVALID_CHARACTER_INDEX		= 21,
	LOGIN_FAIL_14_OVER						= 22,
	LOGIN_FAIL_OVERLAPPED_ID_ANOTHER_SERVER	= 23,
	LOGIN_FAIL_EJECT_USER					= 50,	
};


enum GAME_OBJECT_TYPE
{
	OBJECT_TYPE_MAINPLAYER				= 1,
	OBJECT_TYPE_PLAYER					= 2,
	OBJECT_TYPE_TRADER_MONSTER			= 3,
	OBJECT_TYPE_EFFECT					= 4,
	OBJECT_TYPE_ITEM					= 5,
	OBJECT_TYPE_SPRITE					= 6,
	OBJECT_TYPE_GAME_LIGHT				= 7,
	OBJECT_TYPE_MONSTER					= 8,
	OBJECT_TYPE_WEAPON					= 9,
	OBJECT_TYPE_WEAPON_EFFECT			= 10,
	OBJECT_TYPE_PC_EFFECT				= 11,
	OBJECT_TYPE_GUARDIAN				= 12,
	OBJECT_TYPE_PLANE					= 13,
	OBJECT_TYPE_SELCHAR					= 15,
	OBJECT_TYPE_TILE					= 16,		
	OBJECT_TYPE_SKILL					= 17,
	OBJECT_TYPE_SUMMON					= 18,			// 가디언또는 소환된 몬스터, 소환물 
	OBJECT_TYPE_DAMAGE_USER				= 19,
	OBJECT_TYPE_DAMAGE_MONSTER			= 20
};


enum DUNGEON_JOIN_FAIL
{
	DUNGEON_JOIN_SUCCESS							= 0,
	DUNGEON_JOIN_FAIL_SERVER_IS_NOT_CONNECTED		= 1,
	DUNGEON_JOIN_FAIL_SERVER_INFO_IS_NOT_FOUND		= 2,
	DUNGEON_JOIN_FAIL_USER_ACCEPT_FAIL				= 3,
	DUNGEON_JOIN_FAIL_NOT_ENOUGH_ENTER_KARZ			= 4,
	DUNGEON_JOIN_FAIL_UNKNOWN_DUNGEOIN_ID			= 5,
	DUNGEON_JOIN_FAIL_NOT_MINMAX_LEVEL				= 6,
	DUNGEON_JOIN_FAIL_EVENT_DUNGEON_OPEN_FULL		= 100,
	DUNGEON_JOIN_FAIL_EVENT_DUNGEON_OPEN_TIME_UP	= 101,
	DUNGEON_JOIN_FAIL_INVALID_EVENT_ENTER_LEVEL		= 0xff,
	DUNGEON_JOIN_FAIL_DUNGEON_INFO_IS_NOT_FOUND		= 200,
	DUNGEON_JOIN_FAIL_USER_OVERFLOW					= 201,
	DUNGEON_JOIN_FAIL_UNAUTHORIZED_USER				= 202,
	DUNGEON_JOIN_FAIL_INVALID_CLASS_OR_HEAD			= 203,
	DUNGEON_JOIN_FAIL_INVALID_LAYERINDEX			= 204,
	DUNGEON_JOIN_FAIL_INVALID_START_SPOT			= 205,
	DUNGEON_JOIN_FAIL_INSERTLAYERUSER_FAILED		= 206,
	DUNGOEN_JOIN_FAIL_IMPOSSIBILITY_AREA			= 207
};


enum UPDATE_GAME_STATUS
{
	UPDATE_GAME_INTRO			= 0,
	UPDATE_GAME_LOGIN			= 1,
	UPDATE_GAME_PLAY			= 2,
	UPDATE_GAME_CHAR_SELECT		= 3,	
	UPDATE_GAME_WORLD			= 4,
	UPDATE_GAME_EVENT			= 5,
	MAX_UPDATE_GAME
};


enum ENCOMMAND
{
	COMMAND_WHISPER					= 1,
	COMMAND_MESSAGE					= 2,
	COMMAND_REFUSAL					= 3,
	COMMAND_APPROVAL				= 4,
	COMMAND_GUARDIAN_ATTACK			= 5,
	COMMAND_GUARDIAN_DEFENSE		= 6,
	COMMAND_MONSTER_ATTACK			= 7,
	COMMAND_MONSTER_DEFENSE			= 8,
	COMMAND_PARTY					= 9,
	COMMAND_GUILD					= 10,	
	COMMAND_WHISPER2				= 11,
	COMMAND_GUILD2					= 12,
	COMMAND_PARTY2					= 13,
	COMMAND_PARTYAPPROVE			= 14,
	COMMAND_PARTYREFUSAL			= 15,
	COMMAND_WHISPER3				= 16,
	COMMAND_HELP					= 17,	
	COMMAND_GM_PK_MODE				= 18,	
	COMMNAD_CHARACTERINFO			= 19,
	COMMAND_GM_CHAT_DISABLE			= 20,
	COMMAND_GM_CREATE				= 21,
	COMMAND_GM_REMOVE				= 22,
	COMMAND_GM_POTAL				= 23,
	COMMAND_GM_RECALL				= 24,
	COMMAND_GM_USERPOTAL			= 25,
	COMMAND_CHINA_BILL_REMAINTIME	= 26, 
};

enum CHAT_TYPE
{
	Chat_Type_ALLCHAT	= 0,
	Chat_Type_WHISPER	= 1,
	Chat_Type_GUILD		= 2,
	Chat_Type_PARTY		= 3,
	Chat_Type_FRIEND	= 4,
};

// 파티 설정 : 최덕석 2005.1.25
enum PARTY_CONFIG_ITEM
{
	PARTY_CONFIG_ITEM_FIRST			= 1,		// 습득자 우선
	PARTY_CONFIG_ITEM_KILL			= 2,		// 마지막 타격자
	PARTY_CONFIG_ITEM_RANDOM		= 3,		// 렌덤
};

enum PARTY_CONFIG_EXP
{
	PARTY_CONFIG_EXP_LEVEL			= 1,		// 레벨별 분배
	PARTY_CONFIG_EXP_SHARE			= 2,		// 공통 분배
	PARTY_CONFIG_EXP_KILLER			= 3,		// 보너스 경험치만 분배
};

struct PARTY_CONFIG
{
	PARTY_CONFIG_ITEM item;
	PARTY_CONFIG_EXP exp;

	PARTY_CONFIG()
	{
		item = PARTY_CONFIG_ITEM_FIRST;
		exp = PARTY_CONFIG_EXP_LEVEL;
	}
};

struct PARTY_FRIEND
{
	BYTE bClass;
	BYTE bOnline;
	char szCharacterName[20];
};

#define MAX_CHARACTER_NAME_LENGTH			20
#define MAX_CHARACTER_REAL_LENGTH			16
#define	MAX_CP								20
#define MAX_SKILL_TARGET_COUNT				20
#define MAX_DISAPPEAR_INFO					255
#define MAX_INPUT_BUFFER_SIZE				256
#define	MAX_PARTY_USER						8
#define	MAX_PARTYENTRY_TEXT					32
#define MAX_CP_COOKIE_LENGTH				1024 * 2
#define MAX_EQUIP_POOL						21
#define	MAX_USER_GUARDIAN					5
#define MAX_SKILL							151
#define	MAX_PLAYER_SHOP_INV					10
#define MAX_ID_LENGTH						20
#define MAX_PASSWORD_LENGTH					20
#define	MAX_DUNGEON_NAME_LENGTH				32
#define MAX_GUILD_NAME_LENGTH				20
#define MAX_GUILD_REAL_NAME_LENGTH			10
#define MAX_BILLING_ORDER_COUNT				8
#define MAX_DUNGEON_MEMO_LENGTH				32
#define MAX_CHARACTER_NAME_REAL_LENGTH		16
#define MAX_EQUIP							21
#define MAX_BELT_POOL						8
#define MAX_INV_LARGE_POOL					21
#define MAX_INV_SMALL_POOL					42
#define	MAX_TRADE_POOL						14
#define MAX_UPGRADE_POOL					4
#define MAX_MAKING_POOL						4
#define	MAX_BANK_LARGE_POOL					63
#define	MAX_BANK_SMALL_POOL					70
#define	MAX_INV_GUARDIAN_POOL				5
#define MAX_PLAYERSHOP_POOL					10
#define MAX_GUARDIAN_POOL					1
#define MAX_WORLD_SERVER_NUM				2
#define	MAX_IP_LENGTH						16
#define MAX_ID_REAL_LENGTH					16
#define MAX_PASSWORD_REAL_LENGTH			16
#define MAX_DUNGEON_NUM_PER_SERVERSET		1000// 맵 갯수 모자라지기 때문에 늘렸음: 050202 hwoarang 
#define MAX_USER_PER_DUNGEON				4000
#define MAX_SERVER_TYPE						4
#define MAX_PACKET_NUM						256
#define MAX_USER_CONNECTION					4000 
#define MAX_RANK_REAL_NICKNAME_LENGTH		8
#define MAX_CHARACTER_REAL_NICKNAME_LENGTH	16
#define MAX_WORLD_NUM_PER_SERVER			5		
#define MAX_SECTION_LINK_NUM				20		//한섹션당 링크되는 섹션의 최대 갯수 
#define MAX_DUNGEON_AREA					30
#define MAX_AREA_DUNGEONCOUNT				10
#define	MAX_GUILD_USER						100
#define MAX_CP_TABLE						31
#define MAX_ITEM_STORE_ENTITY				1500
#define MAX_KIND_OF_CLASS					5		// 클래스 갯수.
#define MAX_DUNGEON_TITLE_LENGTH			40
#define MAX_NICK_REAL_LENGTH				16
#define MAX_TILE_WIDTH_NUM					192		// 한맵(던전 한층)당 가질수 있는 타일의 가로갯수 
#define MAX_TILE_HEIGHT_NUM					192		// 한맵(던전 한층)당 가질수 있는 타일의 세로갯수 
#define MAX_SECTION_NUM_PER_LAYER			150		// 한 층당 가질수 있는 최대 섹션 갯수 
#define MAX_LAYER_PER_DUNGEON				20
#define MAX_DUNGEON_PER_SERVER				30		// 한 서버가 가질수 있는 최대 던전 수 
#define MAX_MOVE_SPOT_NUM					10
#define MAX_START_SPOT_NUM					5


#define	POS_SERVER_WORLD					SERVER_TYPE_WORLD
#define	POS_SERVER_DUNGEON					SERVER_TYPE_DUNGEON
#define	POS_SERVER_CONNECT					0xff
#define EVENT_NUM_RECOM_ADD_ITEM			1		//2003년 10월 28일부터 시작되는 이벤트 추천받아 생성된 캐릭터에는 기본 아이템 몇개를 더 넣어줌 
#define EVENT_NUM_PC_ROOM_EXP_TWICE			2		//2003년 12월 31일부터 시작되는 PC방 유저 경험치 2배 이벤트 
#define ACCEPT_ALLOWED_TYPE_NORMAL			1
#define ACCEPT_ALLOWED_TYPE_PORTAL			2
#define	ACCEPT_ALLOWED_TYPE_GAMEROOM		3
#define	__GCTYPE_GUILD__					1
#define	__GCTYPE_CLEN__						2
#define	__GUILD_USER__						1
#define	__GUILD_LIST__						2
#define	__MAX_MESSGAE__						256
#define	GM_COMMAND_PK_MODE					1
#define GM_COMMAND_CHAT_DISABLE				2
#define GM_COMMAND_CREATE					3
#define GM_COMMAND_POTAL					4
#define GM_COMMAND_RECALL					5
#define GM_COMMAND_USERPOTAL				6
#define INVALID_DUNGEON_LAYER				255
#define INVALID_DUNGEON_SECTION				255
#define DEFAULT_DUNGEON_PER_SERVER			5		// 한서버당 평균 몇개의 던전을 가지고 있는지 
#define DEFAULT_ALLOC_NODE_NUM				800
#define BILLING_INFO_SMALL_TIME				1		// 종량제일경우 몇분후에 종료됨을 알려줌 
#define BILLING_INFO_START_BILLING			2		// 새로운 타입의 빌링이 시작됨 
#define TIME_SEC							1
#define	TIME_MIN							2
#define	TIME_HOUR							3
#define ONLY_SEC							4

#	define MAX_GUILD_COUNT					3000

#if defined (CHINA_LOCALIZING)
#	undef	MAX_PASSWORD_REAL_LENGTH			
#	define MAX_PASSWORD_REAL_LENGTH			20
#endif 


#ifdef JAPAN_LOCALIZING
#	define	MAX_PLAYER_SHOP_TITLE			30
#elif defined CHINA_LOCALIZING	
#	define	MAX_PLAYER_SHOP_TITLE			28
#else
#	define	MAX_PLAYER_SHOP_TITLE			40
#endif


#define START	__asm	rdtsc			\
				__asm	push	eax		\
				__asm	push	edx		\


#define END		__asm	rdtsc			\
				__asm	pop		ebx		\
				__asm	pop		ecx		\
				__asm	sub		eax,ecx	\
				__asm	sub		edx,ebx	\
				__asm	int		3		\








