#pragma once


#include "CommonServer.h"


//========================================
// 없어져야 할 define
#define ITEM_DISTRIBUTE				200
#define	ITEM_WEAPONST_INDEX			0
#define	ITEM_WEAPONEND_INDEX		7
#define	ITEM_ARMORST_INDEX			10
#define	ITEM_ARMOREND_INDEX			17
#define ITEM_BAG_INDEX				18
#define	ITEM_GUARDIAN_INDEX			19
#define	ITEM_RIDE_INDEX				20
#define ITEM_MIXUPGRADEST_INDEX		31
#define ITEM_MIXUPGRADEEND_INDEX	33
#define ITEM_UPGRADE_INDEX			34
#define ITEM_LIQUID_INDEX			35
#define ITEM_EDITION_INDEX			36
#define	ITEM_ZODIAC_INDEX			40
#define	ITEM_SUPPLIES_INDEX			50
#define	ITEM_SPECIALST_INDEX		60
#define	ITEM_SPECIALEND_INDEX		66
#define ITEM_MATERIALST_INDEX		70
#define ITEM_MATERIALEND_INDEX		77
#define	ITEM_MAGICARRAY_INDEX		80
#define ITEM_MAGICFIELDARRAY_INDEX	90
#define ITEM_CONSUMABLEST_INDEX		101
#define ITEM_CONSUMABLEEND_INDEX	102
#define	ITEM_MONEY_INDEX			125
#define COPY_CHECK_INV_SMALL		1
#define COPY_CHECK_INV_LARGE		2
#define COPY_CHECK_INV_ALL			3
#define COPY_CHECK_BANK_SMALL		4
#define COPY_CHECK_BANK_LARGE		5
#define COPY_CHECK_BANK_ALL			6
#define COPY_CHECK_EQUIP			7
#define COPY_CHECK_BELT				8
#define COPY_CHECK_ALL				9
enum ITEM_PROPERTY_TYPE
{
	ITEM_PROPERTY_TYPE_WEAPON_ARM1	=	10,		// 한손무기
	ITEM_PROPERTY_TYPE_WEAPON_ARM2	=	20,		// 양손무기
	ITEM_PROPERTY_TYPE_SHIELD		=	30,		// 방패
	ITEM_PROPERTY_TYPE_ARMOR		=	40,		// 방어구
	ITEM_PROPERTY_TYPE_BELT			=	50,		// 벨트
	ITEM_PROPERTY_TYPE_GLOVE		=	60,		// 장갑		
	ITEM_PROPERTY_TYPE_BOOTS		=	70,		// 신발
	ITEM_PROPERTY_TYPE_NECK			=	80,		// 목에 걸리는것
	ITEM_PROPERTY_TYPE_RING			=	90,		// 반지
	ITEM_PROPERTY_TYPE_ONCE			=	100,	// 소모성
};
#define	ITEM_LARGE						1
#define	ITEM_SMALL						2
#define	ITEM_NONE						0
#define	__MAX_ITEM_LARGE_INDEX__		20
#define	__MAX_ITEM_SMALL_INDEX__		70
#define ITEM_DIVIDE_ID_ZODIAC			40

#define __ITEM_MIXUPGRADE_ZODIAC_ARIES__		8000
#define __ITEM_OVERDRIVE_CHK__					8001
#define __ITEM_PORTAL_INDEX__					8002
#define __ITEM_MAKING_INDEX__					8003
#define __ITEM_MIXUPGRADE_ZODIAC_VIRGO__		8005
#define __ITEM_INSURANCE_INDEX__				8006	
#define __ITEM_PORTALUSED_INDEX__				8010

// 2005.02.14 김영대 귀환 스크롤 추가 
#define	__ITEM_PORTAL_VILL1__					8012
#define	__ITEM_PORTAL_VILL2__					8013
#define	__ITEM_PORTAL_VILL3__					8014
#define	__ITEM_PORTAL_VILL4__					8015
#define	__ITEM_PORTAL_VILL5__					8016
#define	__ITEM_PORTAL_VILL6__					8017


#define	__ITEM_GUILD_INDEX__					12200
#define	__ITEM_CLEN_INDEX__						12201

// 선물상자 이벤트 아이템 아이디 
// 2005.02.02 김영대 복주머니로 변경
#define __ITEM_HEROITEM_INDEX__					12403
//#define __ITEM_HEROITEM_INDEX__					13055


#define __ITEM_MIXUPGRADE_EXLIXIR__				32
#define __ITEM_MIXUPGRADE_JEWEL__				33
#define __ITEM_STATUS_INT__						13001
#define __ITEM_SKILL_INT__						13002
#define __ITEM_STATUS_INTSTART__				13006
#define __ITEM_STATUS_INTEND__					13023
#define __ITEM_SKILL_INTSTART__					13024
#define __ITEM_SKILL_INTEND__					13038
#define __ITEM_GUILD_RECALL_INDEX__				16023
#define __ITEM_METERIALS_FIRE_PROPERTY_INDEX__	15335
#define __ITEM_METERIALS_ICE_PROPERTY_INDEX__	15336
#define __ITEM_METERIALS_LIGHT_PROPERTY_INDEX__	15337
#define __ITEM_PARTY_PORTAL1__					16021
#define __ITEM_PARTY_PORTAL2__					16022
#define __ITEM_PARTY_LIFELINK1__				16001
#define __ITEM_PARTY_LIFELINK2__				16002
#define __ITEM_PARTY_LIFELINK3__				16003
#define __ITEM_PARTY_LIFELINK4__				16004
#define __ITEM_PARTY_LIFELINK5__				16005
#define __ITEM_PARTY_AMBUSH1__					16041
#define __ITEM_PARTY_AMBUSH2__					16042
#define __ITEM_PARTY_AMBUSH3__					16043
#define __ITEM_PARTY_AMBUSH4__					16044
#define __ITEM_PARTY_AMBUSH5__					16045
#define __ITEM_PARTY_ST1__						16061
#define __ITEM_PARTY_ST2__						16062
#define __ITEM_PARTY_ST3__						16063
#define __ITEM_PARTY_ST4__						16064
#define __ITEM_PARTY_ST5__						16065
#define __ITEM_KARZ__							25000
#define	ITEM_GUILD_INDEX						12200
#define	ITEM_CLEN_INDEX							12201
#define	MAX_LARGE_ITEM_INDEX					20
#define	MAX_SMALL_ITEM_INDEX					70
#define	ITEM_LIFE_LINK_SUBID					1
#define	ITEM_SYNERGISTIC_TRAINING				2
#define ITEM_AMBUSH_SUBID						3
#define MAX_ITEM_ATTR							8		
#define MAX_ITEM_TYPE							10
#define MAX_ITEM_CLASS							17
#define ITI_TYPE_BASEITEM						1000
#define	ITEM_NUM_PER_OPTION2					10010
#define ITEM_NUM_PER_CLASS						100
#define ITEM_NUM_PER_OPTION						18
#define MAX_BASEITEM_CONSUMABLE_ITEMATTR		5
#define ITEM_PRESENT_BOX_INDEX					66
//========================================


#define ITEM_KIND_WEAPON			0x00001			
#define ITEM_KIND_AROMR				0x00002		
#define ITEM_KIND_BAG				0x00004		
#define	ITEM_KIND_GUARDIAN			0x00008		
#define ITEM_KIND_RIDE				0x00010		
#define ITEM_KIND_MIXUPGRADE		0x00020	
#define ITEM_KIND_UPGRADE			0x00040		
#define ITEM_KIND_LIQUID			0x00080		
#define ITEM_KIND_EDITION			0x00100
#define ITEM_KIND_ZODIAC			0x00200
#define ITEM_KIND_SUPPLIES			0x00400
#define ITEM_KIND_SPECIAL			0x00800
#define ITEM_KIND_MATERIALS			0x01000
#define ITEM_KIND_MAGICARRAY		0x02000	
#define ITEM_KIND_MAGICFIELDARRAY	0x04000
#define ITEM_KIND_CONSUMABLE		0x08000
#define ITEM_KIND_LAND				0x10000	
#define ITEM_KIND_MONEY				0x20000	


#define ITEM_CLASS_SWARD			0
#define ITEM_CLASS_MACE				1
#define ITEM_CLASS_KATAL			2
#define ITEM_CLASS_SWARD2			3
#define ITEM_CLASS_MACE2			4
#define ITEM_CLASS_SPEAR			5
#define ITEM_CLASS_WAND				6
#define ITEM_CLASS_STAFF			7
#define ITEM_CLASS_HELMET			10
#define ITEM_CLASS_ARMOR			11
#define ITEM_CLASS_SHIELD			12
#define ITEM_CLASS_BELT				13
#define ITEM_CLASS_GLOVE			14
#define ITEM_CLASS_BOOTS			15
#define ITEM_CLASS_RING				16
#define ITEM_CLASS_AMULET			17


#define	EQUIP_TYPE_RHAND1			0
#define	EQUIP_TYPE_RHAND2			1
#define	EQUIP_TYPE_RIDE				2
#define	EQUIP_TYPE_HELMET			3
#define	EQUIP_TYPE_BAG				4
#define	EQUIP_TYPE_LHAND1			5
#define	EQUIP_TYPE_LHAND2			6
#define	EQUIP_TYPE_RGLOVE			7
#define	EQUIP_TYPE_MAIL				8
#define	EQUIP_TYPE_AMULE1			9
#define	EQUIP_TYPE_AMULE2			10
#define	EQUIP_TYPE_AMULE3			11
#define	EQUIP_TYPE_BELT				12
#define	EQUIP_TYPE_LGLOVE			13
#define	EQUIP_TYPE_RRING1			14
#define	EQUIP_TYPE_RRING2			15
#define	EQUIP_TYPE_RRING3			16
#define	EQUIP_TYPE_BOOTS			17
#define	EQUIP_TYPE_LRING1			18
#define	EQUIP_TYPE_LRING2			19
#define	EQUIP_TYPE_LRING3			20


enum ITEM_TYPE
{
	ITEM_TYPE_NONE	=				0,
	ITEM_TYPE_LARGE	=				1,
	ITEM_TYPE_SMALL	=				2,
	ITEM_TYPE_MONEY	=				3,
};


enum ITEM_WEAPON_TYPE
{
	ITEM_WEAPON_TYPE_NONE			= 0,
	ITEM_WEAPON_TYPE_ONEHAND		= 1,
	ITEM_WEAPON_TYPE_TWOHAND		= 2,
};


enum ITEM_BAG_TYPE
{
	ITEM_BAG_TYPE_DECREASE_SMALL_BAG		= 1,
	ITEM_BAG_TYPE_INCREASE_TOTAL_BAG		= 2, 
	ITEM_BAG_TYPE_INCREASE_TOTALPER_BAG		= 3, 
};


enum ITEM_LAND_TYPE
{
	ITEM_LAND_TYPE_NONE				= 0,
	ITEM_LAND_TYPE_PLAYTIME			= 1,
	ITEM_LAND_TYPE_SERVERTIME		= 2,
};


enum ITEM_NATIVE
{
	ITEM_NATIVE_PLAYER_START = 0,
	ITEM_NATIVE_EQUIP = 1,
	ITEM_NATIVE_INV_LARGE,
	ITEM_NATIVE_INV_SMALL,
	ITEM_NATIVE_INV_GUARDIAN,
	ITEM_NATIVE_BELT,
	ITEM_NATIVE_BANK_LARGE,
	ITEM_NATIVE_BANK_SMALL,
	ITEM_NATIVE_TRADE,
	ITEM_NATIVE_UPGRADE,
	ITEM_NATIVE_MAKING,
	ITEM_NATIVE_PLAYERSHOP,
	ITEM_NATIVE_GUARDIAN,
	ITEM_NATIVE_PLAYER_END,	
		
	ITEM_NATIVE_TRADERMONSTER_START = 50,
	ITEM_NATIVE_TRADERMONSTER_INV_LARGE = 51,
	ITEM_NATIVE_TRADERMONSTER_INV_SMALL,
	ITEM_NATIVE_TRADERMONSTER_END,
	
	ITEM_NATIVE_TILE_START = 100,
	ITEM_NATIVE_TILE = 101,
	ITEM_NATIVE_TILE_END, 
	
	ITEM_NATIVE_DUNGEONMANAGER_START = 110,
	ITEM_NATIVE_DUNGEONMANAGER = 111,
	ITEM_NATIVE_DUNGEONMANAGER_END, 
	
	ITEM_NATIVE_KARZ_START = 120,
	ITEM_NATIVE_INV_KARZ = 121,
	ITEM_NATIVE_BANK_KARZ,
	ITEM_NATIVE_KARZ_END,	
};


enum ITEM_ATTR_CODE
{
	ITEM_ATTR_NONE						=									0,
	ITEM_ATTR_BLOCK						=									1,		// 방어력.
	ITEM_ATTR_AVOID_POINT				=									2,		// 아이템 재료.
	ITEM_ATTR_AVOID_PERSENT				=									3,		// 공격력.
	ITEM_ATTR_ATTACK_SPEED_POINT		=									4,		// 공격 속도.
	ITEM_ATTR_MOVE_SPEED				=									5,		// 이동 속도.
	ITEM_ATTR_EGO						=									6,		// EGO 상승.
	ITEM_ATTR_STR						=									7,		// STR 상승.
	ITEM_ATTR_DEX						=									8,		// DEX 상승.
	ITEM_ATTR_INT						=									9,		// INT 상승.
	ITEM_ATTR_VIT						=									10,		// VIT 상승.
	ITEM_ATTR_HP_POINT					=									11,		// HP 상승 포인트.
	ITEM_ATTR_HP_PERCENT				=									12,		// HP 상승 퍼센트.
	ITEM_ATTR_SP_POINT					=									13,		// SP 상승 포인트.
	ITEM_ATTR_SP_PERCENT				=									14,		// SP 상승 퍼센트.
	ITEM_ATTR_AA_POINT					=									15,		// 공격 정확도 포인트.
	ITEM_ATTR_AA_PERCENT				=									16,		// 공격 정확도 페센트.
	ITEM_ATTR_FIRERESIST				=									17,		// 화염 저항력.
	ITEM_ATTR_LIGHTRESIST				=									18,		// 전기 저항력.
	ITEM_ATTR_ICERESIST					=									19,		// 얼음 저항력.
	ITEM_ATTR_POIRESIST					=									20,		// 독 저항력.
	ITEM_ATTR_ALLRESIST					=									21,		// 모든 저항력.
	ITEM_ATTR_PHYRESIST					=									22,		// 물리 저항력.
	ITEM_ATTR_ALLSKILL					=									23,		// 올 스킬
	ITEM_ATTR_MANASKILL					=									24,
	ITEM_ATTR_AURASKILL					=									25,
	ITEM_ATTR_DEVINESKILL				=									26,
	ITEM_ATTR_CHAKRASKILL				=									27,
	ITEM_ATTR_SUMMONSKILL				=									28,
	ITEM_ATTR_HEALSPEEDHP				=									29,
	ITEM_ATTR_HEALSPEEDMP				=									30,
	ITEM_ATTR_ALLSTATUS					=									31,
	MAX_ITEM_KIND1_CODE,				
	ITEM_ATTR_LEVEL_PER_MAXHP			=									32,
	ITEM_ATTR_LEVEL_PER_MAXMP			=									33,
	ITEM_ATTR_LEVEL_PER_AA				=									34,
	ITEM_ATTR_LEVEL_PER_AVOID			=									35,
	ITEM_ATTR_BLOCKRATE					=									36,
	ITEM_ATTR_MAGIC_FIND_PBT			=									37,
	ITEM_ATTR_KARZ_GAIN				=										38,		// 카르츠 떨구는 양을 늘려주는 속성.
	ITEM_ATTR_CRITICAL				=										39,
	ITEM_ATTR_SUPER_CRITICAL		=										40,
	ITEM_ATTR_ATTACK_MIN			=										41,
	ITEM_ATTR_ATTACK_MAX			=										42,
	ITEM_ATTR_ATTACK_MAGIC			=										43,
	ITEM_ATTR_ATTACK_FIRE			=										44,
	ITEM_ATTR_ATTACK_ICE			=										45,
	ITEM_ATTR_ATTACK_LIGHT			=										46,
	ITEM_ATTR_ATTACK_POI			=										47,
	ITEM_ATTR_SKILL_DMG_MAGIC		=										48,	
	ITEM_ATTR_SKILL_DMG_FIRE		=										49,
	ITEM_ATTR_SKILL_DMG_ICE			=										50,
	ITEM_ATTR_SKILL_DMG_LIGHT		=										51,
	ITEM_ATTR_SKILL_DMG_POI			=										52,
	ITEM_ATTR_TARGET_ALL_RESIST		=										53,
	ITEM_ATTR_TARGET_FIRE_RESIST	=										54,
	ITEM_ATTR_TARGET_ICE_RESIST		=										55,
	ITEM_ATTR_TARGET_LIGHT_RESIST	=										56,
	ITEM_ATTR_TARGET_POI_RESIST		=										57,
	ITEM_ATTR_TARGET_PHY_RESIST		=										58,
	ITEM_ATTR_TARGET_AVOID			=										59,
	ITEM_ATTR_STUN_TIME				=										60,
	ITEM_ATTR_POI_TIME				=										61,
	ITEM_ATTR_FROZEN_TIME			=										62,
	ITEM_ATTR_FIRE_RESIST_POINT		=										63,
	ITEM_ATTR_ICE_RESIST_POINT		=										64,
	ITEM_ATTR_LIGHT_RESIST_POINT	=										65,
	ITEM_ATTR_POI_RESIST_POINT		=										66,
	ITEM_ATTR_PHY_RESIST_POINT		=										67,
	ITEM_ATTR_ALL_RESIST_POINT		=										68,
	ITEM_ATTR_FIRE_ABSORB_POINT		=										69,
	ITEM_ATTR_FIRE_ABSORB			=										70,
	ITEM_ATTR_ICE_ABSORB_POINT		=										71,
	ITEM_ATTR_ICE_ABSORB			=										72,
	ITEM_ATTR_LIGHT_ABSORB_POINT	=										73,
	ITEM_ATTR_LIGHT_ABSORB			=										74,
	ITEM_ATTR_POI_ABSORB_POINT		=										75,
	ITEM_ATTR_POI_ABSORB			=										76,
	ITEM_ATTR_ALL_ABSORB_POINT		=										77,
	ITEM_ATTR_ALL_ABSORB			=										78,
	ITEM_ATTR_PHY_DMG_TO_SP			=										79,
	ITEM_ATTR_MOP_KILL_TO_SP		=										80,
	ITEM_ATTR_MOP_KILL_TO_HP		=										81,
	ITEM_ATTR_ATTACK_DMG_TO_HP		=										82,
	ITEM_ATTR_ATTACK_DMG_TO_SP		=										83,
	ITEM_ATTR_DMG_REFLECT_POINT		=										84,
	ITEM_ATTR_DMG_REFLECT			=										85,
	ITEM_ATTR_SKILL_LEV_AURA_ALL	=										86,
	ITEM_ATTR_SKILL_LEV_AURA_ACTIVE	=										87,
	ITEM_ATTR_SKILL_LEV_AURA_PACIVE	=										88,
	ITEM_ATTR_SKILL_LEV_AURA_OVERDRIVE		=								89,
	ITEM_ATTR_SKILL_LEV_DIVINE_ALL			=								90,
	ITEM_ATTR_SKILL_LEV_DIVINE_ACTIVE		=								91,
	ITEM_ATTR_SKILL_LEV_DIVINE_PACIVE		=								92,
	ITEM_ATTR_SKILL_LEV_DIVINE_OVERDRIVE	=								93,
	ITEM_ATTR_SKILL_LEV_SUMMON_ALL			=								94,
	ITEM_ATTR_SKILL_LEV_SUMMON_ACTIVE		=								95,
	ITEM_ATTR_SKILL_LEV_SUMMON_PACIVE		=								96,
	ITEM_ATTR_SKILL_LEV_SUMMON_OVERDRIVE	=								97,
	ITEM_ATTR_SKILL_LEV_CHAKRA_ALL			=								98,
	ITEM_ATTR_SKILL_LEV_CHAKRA_ACTIVE		=								99,
	ITEM_ATTR_SKILL_LEV_CHAKRA_PACIVE		=								100,
	ITEM_ATTR_SKILL_LEV_CHAKRA_OVERDRIVE	=								101,
	ITEM_ATTR_SKILL_LEV_MANA_ALL			=								102,
	ITEM_ATTR_SKILL_LEV_MANA_ACTIVE			=								103,
	ITEM_ATTR_SKILL_LEV_MANA_ACTIVE_ICE		=								104,
	ITEM_ATTR_SKILL_LEV_MANA_ACTIVE_FIRE	=								105,
	ITEM_ATTR_SKILL_LEV_MANA_ACTIVE_LIGHT	=								106,
	ITEM_ATTR_SKILL_LEV_MANA_ACTIVE_EARTH	=								107,
	ITEM_ATTR_SKILL_LEV_MANA_PACIVE			=								108,
	ITEM_ATTR_SKILL_LEV_MANA_OVERDRIVE		=								109,
	ITEM_ATTR_SIZE_SCALE					=								110,
	ITEM_ATTR_ATTACK_NOR					=								111,
	ITEM_ATTR_EXP_GAIN						=								112,
	ITEM_ATTR_LEVEL_PER_ALL_MAGIC_RESIST	=								113,
	ITEM_ATTR_LEVEL_PER_FIRE_RESIST			=								114,
	ITEM_ATTR_LEVEL_PER_ICE_RESIST			=								115,
	ITEM_ATTR_LEVEL_PER_LIGHT_RESIST		=								116,
	ITEM_ATTR_LEVEL_PER_POI_RESIST			=								117,
	ITEM_ATTR_LEVEL_PER_PHY_RESIST			=								118,
	ITEM_ATTR_LEVEL_PER_DMG_MIN				=								119,
	ITEM_ATTR_LEVEL_PER_DMG_MAX				=								120,
	ITEM_ATTR_CASTINGTIME					=								121,
	ITEM_ATTR_COOLTIME						=								122,
	ITEM_ATTR_EXP_LOSS						=								123,
	ITEM_ATTR_LEVEL_PER_DMG					=								124,
	ITEM_ATTR_SIZE_SCALE_DECREASE			=								125,
	ITEM_ATTR_SKILL_LEVEL_SKILL_MEDITETION							=			126,
	ITEM_ATTR_SKILL_LEVEL_SKILL_FIREMISSILE							=			127,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_FIREMISSILE			=			128,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_FIREMISSILE			=			129,
	ITEM_ATTR_SKILL_LEVEL_SKILL_FIREBLAZE							=			130,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_FIREBLAZE				=			131,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_FIREBLAZE			=			132,
	ITEM_ATTR_SKILL_LEVEL_SKILL_MAGMAWALL							=			133,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_MAGMAWALL				=			134,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_MAGMAWALL			=			135,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ICEMISSILE							=			136,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_ICEMISSILE			=			137,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_ICEMISSILE			=			138,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ICEWAVE								=			139,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_ICEWAVE				=			140,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_ICEWAVE				=			141,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ICEWALL								=			142,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_ICEWALL				=			143,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_ICEWALL				=			144,
	ITEM_ATTR_SKILL_LEVEL_SKILL_LIGHTNING							=			145,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_LIGHTNING				=			146,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_LIGHTNING			=			147,
	ITEM_ATTR_SKILL_LEVEL_SKILL_AIREALCOAT							=			148,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_AIREALCOAT			=			149,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_AIREALCOAT			=			150,
	ITEM_ATTR_SKILL_LEVEL_SKILL_THUNDERSTORM						=			151,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_THUNDERSTORM			=			152,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_THUNDERSTORM		=			153,
	ITEM_ATTR_SKILL_LEVEL_SKILL_LANDINGSUPPORT						=			154,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_LANDINGSUPPORT		=			155,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_LANDINGSUPPORT		=			156,
	ITEM_ATTR_SKILL_LEVEL_SKILL_EARTHQUAKE							=			157,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_EARTHQUAKE			=			158,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_EARTHQUAKE			=			159,
	ITEM_ATTR_SKILL_LEVEL_SKILL_METEOR								=			160,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_METEOR				=			161,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_METEOR				=			162,
	ITEM_ATTR_SKILL_LEVEL_SKILL_MANAEXPAND							=			163,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_MANAEXPAND			=			164,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_MANAEXPAND			=			165,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SPEEDCASTING						=			166,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SPEEDCASTING			=			167,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SPEEDCASTING		=			168,
	ITEM_ATTR_SKILL_LEVEL_SKILL_EXPLOSION							=			169,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_EXPLOSION				=			170,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_EXPLOSION			=			171,
	ITEM_ATTR_SKILL_LEVEL_SKILL_CONCENTRATION						=			172,
	ITEM_ATTR_SKILL_LEVEL_SKILL_REGENERATION						=			176,
	ITEM_ATTR_SKILL_LEVEL_SKILL_WEAPONMASTERY						=			177,
	ITEM_ATTR_SKILL_LEVEL_SKILL_DEFENSEMASTERY						=			178,
	ITEM_ATTR_SKILL_LEVEL_SKILL_AURARECHARGE						=			179,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_AURARECHARGE			=			180,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_AURARECHARGE		=			181,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ZEAL								=			182,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_ZEAL					=			183,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_ZEAL				=			184,
	// 050122 jaewon
	// Item_SET_INFO 테이블과 일치 시킴.
	// 현재 Itme_SET_INFO 와 Define이 일치 하지 않음. 
	// TODO : 병언씨와 작업 완료 필요.
	ITEM_ATTR_SKILL_LEVEL_SKILL_BASH								=			182, 
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_BASH					=			186,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_BASH				=			187,
	ITEM_ATTR_SKILL_LEVEL_SKILL_LIGHTNINGBREAK						=			188,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_LIGHTNINGBREAK		=			189,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_LIGHTNINGBREAK		=			190,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SILENTBRANDYSHIP					=			191,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SILENTBRANDYSHIP		=			192,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SILENTBRANDYSHIP	=			193,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ANTAGONIZE							=			194,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_ANTAGONIZE			=			195,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_ANTAGONIZE			=			196,
	ITEM_ATTR_SKILL_LEVEL_SKILL_AURABATTLER							=			197,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_AURABATTLER			=			198,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_AURABATTLER			=			199,
	ITEM_ATTR_SKILL_LEVEL_SKILL_LIFEFORCE							=			200,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_LIFEFORCE				=			201,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_LIFEFORCE			=			202,
	ITEM_ATTR_SKILL_LEVEL_SKILL_PRAY								=			203,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_PRAY					=			204,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_PRAY				=			205,
	ITEM_ATTR_SKILL_LEVEL_SKILL_BLESSING							=			206,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_BLESSING				=			207,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_BLESSING			=			208,
	ITEM_ATTR_SKILL_LEVEL_SKILL_WINDTALES							=			209,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_WINDTALES				=			210,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_WINDTALES			=			211,
	ITEM_ATTR_SKILL_LEVEL_SKILL_HOLDSHIELD							=			212,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_HOLDSHIELD			=			213,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_HOLDSHIELD			=			214,
	ITEM_ATTR_SKILL_LEVEL_SKILL_WINDFORCE							=			215,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_WINDFORCE				=			216,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_WINDFORCE			=			217,
	ITEM_ATTR_SKILL_LEVEL_SKILL_AMFLEAFIRE							=			218,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_AMFLEAFIRE			=			219,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_AMFLEAFIRE			=			220,
	ITEM_ATTR_SKILL_LEVEL_SKILL_HOLYPRESSURE						=			221,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_HOLYPRESSURE			=			222,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_HOLYPRESSURE		=			223,
	ITEM_ATTR_SKILL_LEVEL_SKILL_APSOLUTMAGICBARRIER					=			224,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_APSOLUTMAGICBARRIER	=			225,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_APSOLUTMAGICBARRIER	=		226,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SPELLBINDING						=		227,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SPELLBINDING			=		228,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SPELLBINDING		=		229,
	ITEM_ATTR_SKILL_LEVEL_SKILL_DOMENATION							=		230,
	ITEM_ATTR_SKILL_LEVEL_SKILL_MIRACULOUSHEART						=		231,
	ITEM_ATTR_SKILL_LEVEL_SKILL_ARCANUMSKIN							=		232,
	ITEM_ATTR_SKILL_LEVEL_SKILL_FRENZY								=		233,
	ITEM_ATTR_SKILL_LEVEL_SKILL_CALMDOWN							=		234,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_CALMDOWN				=		235,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_CALMDOWN			=		236,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SLEEP								=		237,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SLEEP					=		238,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SLEEP				=		239,
	ITEM_ATTR_SKILL_LEVEL_SKILL_CONFUSE								=		240,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_CONFUSE				=		241,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_CONFUSE				=		242,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SOULBLASTER							=		243,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SOULBLASTER			=		244,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SOULBLASTER			=		245,
	ITEM_ATTR_SKILL_LEVEL_SKILL_MINDCONTROL							=		246,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_MINDCONTROL			=		247,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_MINDCONTROL			=		248,
	ITEM_ATTR_SKILL_LEVEL_SKILL_RAGE								=		249,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_RAGE					=		250,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_RAGE				=		251,
	ITEM_ATTR_SKILL_LEVEL_SKILL_REDELEMENTAL						=		252,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_REDELEMENTAL			=		253,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_REDELEMENTAL		=		254,
	ITEM_ATTR_SKILL_LEVEL_SKILL_BLUEELEMENTAL						=		255,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_BLUEELEMENTAL			=		256,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_BLUEELEMENTAL		=		257,
	ITEM_ATTR_SKILL_LEVEL_SKILL_GREENELEMENTAL						=		258,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_GREENELEMENTAL		=		259,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_GREENELEMENTAL		=		260,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SPEEDOVER							=		261,
	ITEM_ATTR_SKILL_LEVEL_SKILL_DODGE								=		262,
	ITEM_ATTR_SKILL_LEVEL_SKILL_POISONING							=		263,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_POISONING				=		264,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_POISONING			=		265,
	ITEM_ATTR_SKILL_LEVEL_SKILL_CHAINATTACKER						=		266,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_CHAINATTACKER			=		267,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_CHAINATTACKER		=		268,
	ITEM_ATTR_SKILL_LEVEL_SKILL_BLASTQUAKE							=		269,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_BLASTQUAKE			=		270,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_BLASTQUAKE			=		271,
	ITEM_ATTR_SKILL_LEVEL_SKILL_IRONSKIN							=		272,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_IRONSKIN				=		273,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_IRONSKIN			=		274,
	ITEM_ATTR_SKILL_LEVEL_SKILL_HIDING								=		275,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_HIDING				=		276,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_HIDING				=		277,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SPELLTRAP							=		278,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SPELLTRAP				=		279,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SPELLTRAP			=		280,
	ITEM_ATTR_SKILL_LEVEL_SKILL_PRESSURE							=		281,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_PRESSURE				=		282,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_PRESSURE			=		283,
	ITEM_ATTR_SKILL_LEVEL_SKILL_LIFEEXPLOSION						=		284,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_LIFEEXPLOSION			=		285,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_LIFEEXPLOSION		=		286,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SYLPHID								=		287,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SYLPHID				=		288,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SYLPHID				=		289,
	ITEM_ATTR_SKILL_LEVEL_SKILL_SHAUT								=		290,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_SHAUT					=		291,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_SHAUT				=		292,
	ITEM_ATTR_SKILL_LEVEL_SKILL_BERSERK								=		293,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACK_SKILL_BERSERK				=		294,
	ITEM_ATTR_SKILL_CASTING_WHEN_ATTACKED_SKILL_BERSERK				=		295,
	ITEM_ATTR_SKILL_CASTING_WHEN_DEAD_SKILL_TREEAGION				=		296,
	ITEM_ATTR_OPTION_INCREASE_WHEN_CHAR_BIRTHDAY					=		297,
	ITEM_ATTR_OPTION_INCREASE_WHEN_MASTER_BIRTHDAY					=		298,
	ITEM_ATTR_ONLY_EFFECT_XMAS										=		299,
	ITEM_ATTR_ONLY_EFFECT_SPECIAL_DAY								=		300,
	ITEM_ATTR_OPTION_INCREASE_WHEN_NIGHTTIME						=		301,
	ITEM_ATTR_OPTION_INCREASE_WHEN_DAYTIME							=		302,
	ITEM_ATTR_ONLY_EFFECT_WHEN_NIGHTTIME							=		303,
	ITEM_ATTR_ONLY_EFFECT_WHEN_DAYTIME								=		304,
	ITEM_ATTR_DESTROYED_WHEN_DUEDATE								=		305,
	ITEM_ATTR_DEAD_EXP_LOSS_DECREASE								=		306,
	ITEM_ATTR_DEAD_EXP_LOSS_INCREASE								=		307,
	ITEM_ATTR_FREE_OVERDRIVE_SKILL									=		308,
	ITEM_ATTR_FREE_POTAL											=		309,
	MAX_ITEM_KIND2_CODE
};